CREATE TABLE "FullStatus" (
    "FullStatusID" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "Status" VARCHAR2(10) NOT NULL,
    CONSTRAINT "uq_status" UNIQUE ("Status")
);

CREATE TABLE "ContainerSize" (
    "SizeID" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "SizeContainer" NUMBER NOT NULL,
    CONSTRAINT "chk_container_size_positive" CHECK ("SizeContainer" >= 0),
    CONSTRAINT "uq_container_size" UNIQUE ("SizeContainer")
);
CREATE TABLE "VehicleType" (
    "VehicleTypeID" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "VehicleTypeName" VARCHAR2(50) NOT NULL,
    CONSTRAINT "uq_vehicle_type_name" UNIQUE ("VehicleTypeName")
);

CREATE TABLE "ContainerType" (
    "TypeID" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "TypeName" VARCHAR2(20) NOT NULL,
    "TypeCode" CHAR(3) NOT NULL,
    "Description" VARCHAR2(255),
    CONSTRAINT "uq_container_type_name_code" UNIQUE ("TypeName", "TypeCode")
);
CREATE TABLE "ContainerOwner" (
    "OwnerID" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL, 
    "OwnerName" VARCHAR2(100) NOT NULL, 
    "OwnerCode" VARCHAR2(5) NOT NULL, 
    "ContactInfo" VARCHAR2(100),  
    "CompanyName" VARCHAR2(100), 
    "ContainerCount" NUMBER DEFAULT 0,
    CONSTRAINT "uq_owner_name_code" UNIQUE ("OwnerName", "OwnerCode"),
    CONSTRAINT "chk_container_count" CHECK ("ContainerCount" >= 0)
);

CREATE TABLE "Ship" (
    "ShipID" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "ShipName" VARCHAR2(100) NOT NULL,
    "Status" VARCHAR2(30) NOT NULL
);

CREATE TABLE "Voyage" (
    "VoyageID" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "VoyageNumber" VARCHAR2(10) NOT NULL,
    "ShipID" NUMBER NOT NULL,
    "DepartureDate" DATE NOT NULL,
    "ArrivalDate" DATE,
    CONSTRAINT "fk_ship" FOREIGN KEY ("ShipID") REFERENCES "Ship"("ShipID")
);

CREATE TABLE "LocationStatus" (
    "LocationStatusID" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "Status" VARCHAR2(10) NOT NULL
);

CREATE TABLE "ContainerStatus" (
    "ContainerStatusID" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "ContainerStatus" VARCHAR2(100) NOT NULL
);
CREATE TABLE "LineOperator" (
    "LineOperatorID" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,  
    "LineOperatorName" VARCHAR2(100) NOT NULL,
    "LineOperatorCode" VARCHAR2(5) NOT NULL,
    "ContactInfo" VARCHAR2(50),
    "CompanyName" VARCHAR2(100),
    "ActiveContracts" NUMBER DEFAULT 0
);

CREATE TABLE "Depot" (
    "DepotID" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "DepotName" VARCHAR2(50) NOT NULL,
    "Location" VARCHAR2(100),
    "BlockCapacity" NUMBER,
    "Contact" VARCHAR2(50)
);

CREATE TABLE "UserAccount" (
    "UserID" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "UserName" VARCHAR2(20) NOT NULL,
    "UserPassword" VARCHAR2(20) NOT NULL
);

CREATE TABLE "VirtualBlock" (
    "VirtualBlockID" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "BlockName" VARCHAR2(10) NOT NULL,
    "Description" VARCHAR2(200),
    "DepotID" NUMBER NOT NULL,  
    CONSTRAINT "fk_depot"
        FOREIGN KEY ("DepotID") 
        REFERENCES "Depot" ("DepotID")
);

CREATE TABLE "ContainerBlock" (
    "BlockID" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "BayRange" NUMBER CHECK ("BayRange" BETWEEN 1 AND 5),
    "RowRange" NUMBER CHECK ("RowRange" BETWEEN 1 AND 10),
    "TierRange" NUMBER CHECK ("TierRange" BETWEEN 1 AND 5),
    "DepotID" NUMBER,
    CONSTRAINT "fk_depot2"
        FOREIGN KEY ("DepotID") 
        REFERENCES "Depot" ("DepotID")
);

CREATE TABLE "Command" (
    "CommandID" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "TaxCode" VARCHAR2(20),
    "MovementType" VARCHAR2(5) NOT NULL,
    "CustomerName" VARCHAR2(100),
    "Deadline" DATE,
    "CreateDate" DATE,
    "ContainerQuantity" NUMBER,
    "LineOperatorID" NUMBER,
    "VoyageID" NUMBER,
    CONSTRAINT "fk_voyage"
        FOREIGN KEY ("VoyageID") 
        REFERENCES "Voyage" ("VoyageID"),
    CONSTRAINT "fk_line_operator"
        FOREIGN KEY ("LineOperatorID") 
        REFERENCES "LineOperator" ("LineOperatorID")
);
CREATE TABLE "Container" (
    "ContainerNumber" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "ISO" VARCHAR2(20),
    "MaximumWeight" NUMBER,
    "TareWeight" NUMBER,
    "DateOfManufacture" DATE,
    "SizeID" NUMBER,
    "ContainerStatusID" NUMBER,
    "OwnerID" NUMBER,
    "ContainerTypeID" NUMBER,
    "VirtualBlockID" NUMBER,
    "LocationStatusID" NUMBER,
    "LineOperatorID" NUMBER,
    "FullStatusID" NUMBER,
    CONSTRAINT "fk_size"
        FOREIGN KEY ("SizeID") 
        REFERENCES "ContainerSize" ("SizeID"),
    CONSTRAINT "fk_container_status"
        FOREIGN KEY ("ContainerStatusID") 
        REFERENCES "ContainerStatus" ("ContainerStatusID"),
    CONSTRAINT "fk_owner"
        FOREIGN KEY ("OwnerID") 
        REFERENCES "ContainerOwner" ("OwnerID"),
    CONSTRAINT "fk_container_type"
        FOREIGN KEY ("ContainerTypeID") 
        REFERENCES "ContainerType" ("TypeID"),
    CONSTRAINT "fk_virtual_block"
        FOREIGN KEY ("VirtualBlockID") 
        REFERENCES "VirtualBlock" ("VirtualBlockID"),
    CONSTRAINT "fk_location_status"
        FOREIGN KEY ("LocationStatusID") 
        REFERENCES "LocationStatus" ("LocationStatusID"),
    CONSTRAINT "fk_line_operator2"
        FOREIGN KEY ("LineOperatorID") 
        REFERENCES "LineOperator" ("LineOperatorID"),
    CONSTRAINT "fk_full_status"
        FOREIGN KEY ("FullStatusID") 
        REFERENCES "FullStatus" ("FullStatusID"),
    CONSTRAINT "chk_virtual_block_null" CHECK ("LocationStatusID" = 2 OR "VirtualBlockID" IS NULL)
);

CREATE TABLE "LifeCycle" (
    "LifeCycleID" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ContainerNumber" NUMBER NOT NULL,  -- Tham chi?u t?i b?ng Container
    "EntryDate" DATE NOT NULL,  -- Ngày container nh?p bãi
    "ExitDate" DATE,
    CONSTRAINT "fk_container_life" FOREIGN KEY ("ContainerNumber") REFERENCES "Container" ("ContainerNumber")
);

CREATE TABLE "PositionContainer" (
    "PositionID" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "Status" VARCHAR2(50),
    "Bay" NUMBER,
    "RowNumber" NUMBER,
    "TierNumber" NUMBER,
    "ContainerNumber" NUMBER,
    "BlockID" NUMBER,
    CONSTRAINT "fk_container2"
        FOREIGN KEY ("ContainerNumber") 
        REFERENCES "Container" ("ContainerNumber"),
    CONSTRAINT "fk_block"
        FOREIGN KEY ("BlockID") 
        REFERENCES "ContainerBlock" ("BlockID")
);

CREATE TABLE "Vehicle" (
    "VehicleID" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "LicensePlate" VARCHAR2(15) NOT NULL,
    "DriverName" VARCHAR2(30),
    "DriverContact" VARCHAR2(15),
    "VehicleCapacity" NUMBER,
    "CompanyName" VARCHAR2(50),
    "Status" VARCHAR2(30) NOT NULL,
    "VehicleTypeID" NUMBER NOT NULL,
    CONSTRAINT "fk_vehicle_type"
        FOREIGN KEY ("VehicleTypeID")
        REFERENCES "VehicleType" ("VehicleTypeID")
);
CREATE TABLE "IOManagement" (
    "ManageID" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "CreateDate" DATE,
    "VehicleID" NUMBER,
    "ContainerNumber" NUMBER,
    "CommandID" NUMBER,
    "UserID" NUMBER,
    CONSTRAINT "fk_vehicle"
        FOREIGN KEY ("VehicleID") 
        REFERENCES "Vehicle" ("VehicleID"),
    CONSTRAINT "fk_container"
        FOREIGN KEY ("ContainerNumber") 
        REFERENCES "Container" ("ContainerNumber"),
    CONSTRAINT "fk_command"
        FOREIGN KEY ("CommandID") 
        REFERENCES "Command" ("CommandID"),
    CONSTRAINT "fk_user"
        FOREIGN KEY ("UserID") 
        REFERENCES "UserAccount" ("UserID")
);
--trigger--------------------------------------------------------------------------
--trigger check bay row tier range
CREATE OR REPLACE TRIGGER "trg_check_position_range"
BEFORE INSERT OR UPDATE ON "PositionContainer"
FOR EACH ROW
DECLARE
    v_bay_range NUMBER;
    v_row_range NUMBER;
    v_tier_range NUMBER;
BEGIN
    BEGIN
        SELECT "BayRange", "RowRange", "TierRange"
        INTO v_bay_range, v_row_range, v_tier_range
        FROM "ContainerBlock"
        WHERE "BlockID" = :NEW."BlockID";

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20004, 'BlockID ' || :NEW."BlockID" || ' does not exist in ContainerBlock.');
        WHEN TOO_MANY_ROWS THEN
            RAISE_APPLICATION_ERROR(-20005, 'Multiple rows found for BlockID ' || :NEW."BlockID" || '.');
    END;

    IF :NEW."Bay" > v_bay_range THEN
        RAISE_APPLICATION_ERROR(-20001, 'Bay value exceeds the maximum range for BlockID ' || :NEW."BlockID");
    END IF;

    IF :NEW."RowNumber" > v_row_range THEN
        RAISE_APPLICATION_ERROR(-20002, 'Row value exceeds the maximum range for BlockID ' || :NEW."BlockID");
    END IF;

    IF :NEW."TierNumber" > v_tier_range THEN
        RAISE_APPLICATION_ERROR(-20003, 'Tier value exceeds the maximum range for BlockID ' || :NEW."BlockID");
    END IF;
END;
/

--trigger ki?m tra không ???c t?n t?i 1 container v?i 2 v? trí active
CREATE OR REPLACE TRIGGER "trg_check_active_status"
BEFORE INSERT OR UPDATE ON "PositionContainer"
FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    -- Ki?m tra s? l??ng ghi v?i cùng ContainerNumber và Status = 'active'
    SELECT COUNT(*)
    INTO v_count
    FROM "PositionContainer"
    WHERE "ContainerNumber" = :NEW."ContainerNumber"
      AND "Status" = 'active'
      AND ("PositionID" <> :NEW."PositionID" OR :NEW."PositionID" IS NULL);

    -- N?u ?ã có b?n ghi active, không cho phép thêm b?n ghi m?i v?i Status = 'active'
    IF v_count > 0 AND :NEW."Status" = 'active' THEN
        RAISE_APPLICATION_ERROR(-20001, 'ContainerNumber cannot have multiple records with status ''active''.');
    END IF;
END;
/
--check bay chan le xep cont 40 20
CREATE OR REPLACE TRIGGER "check_container_position"
BEFORE INSERT OR UPDATE ON "PositionContainer"
FOR EACH ROW
DECLARE
    v_container_size NUMBER; -- Kích th??c container (20 ho?c 40 feet)
BEGIN
    -- Truy v?n kích th??c container t? b?ng ContainerSize
    BEGIN
        SELECT cs."SizeContainer"
        INTO v_container_size
        FROM "Container" c
        JOIN "ContainerSize" cs ON c."SizeID" = cs."SizeID"
        WHERE c."ContainerNumber" = :NEW."ContainerNumber";
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20004, 'Container does not exist.');
    END;

    -- Ki?m tra n?u kích th??c container là 20 feet và bay là s? ch?n
    IF v_container_size = 20 THEN
        IF MOD(:NEW."Bay", 2) = 0 THEN
            RAISE_APPLICATION_ERROR(-20001, '20 feet containers cannot be placed in even-numbered bays.');
        END IF;
    -- Ki?m tra n?u kích th??c container là 40 feet và bay là s? l?
    ELSIF v_container_size = 40 THEN
        IF MOD(:NEW."Bay", 2) <> 0 THEN
            RAISE_APPLICATION_ERROR(-20002, '40 feet containers cannot be placed in odd-numbered bays.');
        END IF;
    ELSE
        RAISE_APPLICATION_ERROR(-20003, 'Invalid container size.');
    END IF;
END;
/

--trigger check khong the ton tai 2 cont cung 1 cho
CREATE OR REPLACE TRIGGER "check_active_container_position"
BEFORE INSERT OR UPDATE ON "PositionContainer"
FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM "PositionContainer"
    WHERE "Bay" = :NEW."Bay"
      AND "RowNumber" = :NEW."RowNumber"
      AND "TierNumber" = :NEW."TierNumber"
      AND "BlockID" = :NEW."BlockID"
      AND "Status" = 'active'
      AND "PositionID" != :NEW."PositionID";

    IF v_count > 0 AND :NEW."Status" = 'active' THEN
        RAISE_APPLICATION_ERROR(-20001, 'This position already has an active container.');
    END IF;
END;
/

--check location status vs position status
CREATE OR REPLACE TRIGGER trg_check_container_position_active
BEFORE INSERT OR UPDATE ON "PositionContainer"
FOR EACH ROW
DECLARE
    v_location_status VARCHAR2(10);
BEGIN
    -- L?y LocationStatus c?a Container t??ng ?ng
    SELECT ls."Status"
    INTO v_location_status
    FROM "Container" c
    JOIN "LocationStatus" ls ON c."LocationStatusID" = ls."LocationStatusID"
    WHERE c."ContainerNumber" = :NEW."ContainerNumber";

    -- Ki?m tra n?u PositionContainer.Status là 'Active' thì LocationStatus ph?i là 'InBlock'
    IF :NEW."Status" = 'active' AND v_location_status != 'InBlock' THEN
        RAISE_APPLICATION_ERROR(-20001, 'Container location status must be "InBlock" for active position.');
    END IF;
END;
/

--insert-----------------------------------------------------------------------------------------------------
-- FullStatus
INSERT INTO "FullStatus" ("Status") VALUES ('Full');
INSERT INTO "FullStatus" ("Status") VALUES ('Empty');

-- ContainerSize
INSERT INTO "ContainerSize" ("SizeContainer") VALUES (20);
INSERT INTO "ContainerSize" ("SizeContainer") VALUES (40);
INSERT INTO "ContainerSize" ("SizeContainer") VALUES (45);

-- VehicleType
INSERT INTO "VehicleType" ("VehicleTypeName") VALUES ('Container Truck');
INSERT INTO "VehicleType" ("VehicleTypeName") VALUES ('Forklift');
INSERT INTO "VehicleType" ("VehicleTypeName") VALUES ('Cranes');
INSERT INTO "VehicleType" ("VehicleTypeName") VALUES ('Reefer Truck');
INSERT INTO "VehicleType" ("VehicleTypeName") VALUES ('Flatbed Truck');

-- ContainerType
INSERT INTO "ContainerType" ("TypeName", "TypeCode", "Description") VALUES ('Dry Container', 'D', 'Standard dry container for general cargo.');
INSERT INTO "ContainerType" ("TypeName", "TypeCode", "Description") VALUES ('Reefer Container', 'R', 'Refrigerated container for perishable goods.');
INSERT INTO "ContainerType" ("TypeName", "TypeCode", "Description") VALUES ('Open Top Container', 'O', 'Container with an open top for oversized cargo.');
INSERT INTO "ContainerType" ("TypeName", "TypeCode", "Description") VALUES ('Flat Rack Container', 'F', 'Flat container with collapsible sides for heavy or oversized cargo.');
INSERT INTO "ContainerType" ("TypeName", "TypeCode", "Description") VALUES ('High Cube Container', 'H', 'Taller than standard dry container, used for oversized cargo.');
INSERT INTO "ContainerType" ("TypeName", "TypeCode", "Description") VALUES ('Tank Container', 'T', 'Specialized container for transporting liquids.');

-- ContainerOwner
INSERT INTO "ContainerOwner" ("OwnerName", "OwnerCode", "ContactInfo", "CompanyName", "ContainerCount") 
VALUES ('CMA CGM', 'CMA', '0212345678', 'CMA CGM S.A.', 10);
INSERT INTO "ContainerOwner" ("OwnerName", "OwnerCode", "ContactInfo", "CompanyName", "ContainerCount") 
VALUES ('Mediterranean Shipping Company', 'MSC', '0212345679', 'Mediterranean Shipping Company S.A.', 8);
INSERT INTO "ContainerOwner" ("OwnerName", "OwnerCode", "ContactInfo", "CompanyName", "ContainerCount") 
VALUES ('Hyundai Merchant Marine', 'HMM', '0212345680', 'Hyundai Merchant Marine Co., Ltd.', 5);

-- Ship
INSERT INTO "Ship" ("ShipName", "Status") VALUES ('Evergreen Ever Ace', 'Active');
INSERT INTO "Ship" ("ShipName", "Status") VALUES ('HMM Algeciras', 'Active');
INSERT INTO "Ship" ("ShipName", "Status") VALUES ('MSC Gülsün', 'InActive');
INSERT INTO "Ship" ("ShipName", "Status") VALUES ('CMA CGM Jacques Saadé', 'Active');
-- Voyage
INSERT INTO "Voyage" ("VoyageNumber", "ShipID", "DepartureDate", "ArrivalDate") 
VALUES ('CSCL001', 1, TO_DATE('2024-01-01', 'YYYY-MM-DD'), TO_DATE('2024-01-15', 'YYYY-MM-DD'));

INSERT INTO "Voyage" ("VoyageNumber", "ShipID", "DepartureDate", "ArrivalDate") 
VALUES ('MSC002', 2, TO_DATE('2024-02-01', 'YYYY-MM-DD'), TO_DATE('2024-02-20', 'YYYY-MM-DD'));

INSERT INTO "Voyage" ("VoyageNumber", "ShipID", "DepartureDate") 
VALUES ('ONE003', 3, TO_DATE('2024-03-01', 'YYYY-MM-DD'));

INSERT INTO "Voyage" ("VoyageNumber", "ShipID", "DepartureDate", "ArrivalDate") 
VALUES ('MAEU004', 4, TO_DATE('2024-04-01', 'YYYY-MM-DD'), TO_DATE('2024-04-18', 'YYYY-MM-DD'));

-- LocationStatus
INSERT INTO "LocationStatus" ("Status") VALUES ('InBlock');
INSERT INTO "LocationStatus" ("Status") VALUES ('Movement');
INSERT INTO "LocationStatus" ("Status") VALUES ('Complete');

-- ContainerStatus
-- Tình tr?ng 1: Không h? h?ng
INSERT INTO "ContainerStatus" ("ContainerStatus") VALUES ('No Damage');
-- Tình tr?ng 2: H? h?ng nh?
INSERT INTO "ContainerStatus" ("ContainerStatus") VALUES ('Minor Damage');
-- Tình tr?ng 3: H? h?ng n?ng
INSERT INTO "ContainerStatus" ("ContainerStatus") VALUES ('Major Damage');
-- Tình tr?ng 4: Móp méo
INSERT INTO "ContainerStatus" ("ContainerStatus") VALUES ('Bent');
-- Tình tr?ng 5: N?t
INSERT INTO "ContainerStatus" ("ContainerStatus") VALUES ('Cracked');
-- Tình tr?ng 6: R? sét
INSERT INTO "ContainerStatus" ("ContainerStatus") VALUES ('Rusty');

-- LineOperator
INSERT INTO "LineOperator" ("LineOperatorName", "LineOperatorCode", "ContactInfo", "CompanyName", "ActiveContracts")
VALUES ('CMA CGM', 'CMA', 'contact@cma-cgm.com', 'CMA CGM Group', 15);

INSERT INTO "LineOperator" ("LineOperatorName", "LineOperatorCode", "ContactInfo", "CompanyName", "ActiveContracts")
VALUES ('Mediterranean Shipping Company', 'MSC', 'info@msc.com', 'Mediterranean Shipping Company', 20);

INSERT INTO "LineOperator" ("LineOperatorName", "LineOperatorCode", "ContactInfo", "CompanyName", "ActiveContracts")
VALUES ('Hyundai Merchant Marine', 'HMM', 'support@hmm21.com', 'Hyundai Merchant Marine', 10);

INSERT INTO "LineOperator" ("LineOperatorName", "LineOperatorCode", "ContactInfo", "CompanyName", "ActiveContracts")
VALUES ('Evergreen Marine', 'EGL', 'service@evergreen-marine.com', 'Evergreen Marine Corp', 12);

INSERT INTO "LineOperator" ("LineOperatorName", "LineOperatorCode", "ContactInfo", "CompanyName", "ActiveContracts")
VALUES ('ONE Line', 'ONE', 'customer.service@one-line.com', 'Ocean Network Express', 8);
-- Depot
INSERT INTO "Depot" ("DepotName", "Location", "BlockCapacity", "Contact")
VALUES ('Depot 1', 'Location 1', 10, 'contact1@example.com');
-- UserAccount
INSERT INTO "UserAccount" ("UserName", "UserPassword")
VALUES ('admin', '123');
-- VirtualBlock
INSERT INTO "VirtualBlock" ("BlockName", "Description", "DepotID")
VALUES ('BlockA', 'Virtual block for storage of large containers.', 1);
-- ContainerBlock
INSERT INTO "ContainerBlock" ("BayRange", "RowRange", "TierRange", "DepotID") VALUES (3, 5, 4, 1);
INSERT INTO "ContainerBlock" ("BayRange", "RowRange", "TierRange", "DepotID") VALUES (4, 6, 5, 1);
-- Command
INSERT INTO "Command" ("TaxCode", "MovementType", "CustomerName", "Deadline", "CreateDate", "ContainerQuantity", "LineOperatorID", "VoyageID") 
VALUES ('123456789', 'IN', 'Company A', TO_DATE('2024-09-15', 'YYYY-MM-DD'), SYSDATE, 18, 1, 1);
INSERT INTO "Command" ("TaxCode", "MovementType", "CustomerName", "Deadline", "CreateDate", "ContainerQuantity", "LineOperatorID", "VoyageID") 
VALUES ('987654321', 'OUT', 'Company B', TO_DATE('2024-10-01', 'YYYY-MM-DD'), SYSDATE, 50, 2, 2);
INSERT INTO "Command" ("TaxCode", "MovementType", "CustomerName", "Deadline", "CreateDate", "ContainerQuantity", "LineOperatorID", "VoyageID") 
VALUES ('112233445', 'IN', 'Company C', TO_DATE('2024-11-10', 'YYYY-MM-DD'), SYSDATE, 44, 3, 3);
INSERT INTO "Command" ("TaxCode", "MovementType", "CustomerName", "Deadline", "CreateDate", "ContainerQuantity", "LineOperatorID", "VoyageID") 
VALUES ('556677889', 'OUT', 'Company D', TO_DATE('2024-12-05', 'YYYY-MM-DD'), SYSDATE, 66, 4, 4);
INSERT INTO "Command" ("TaxCode", "MovementType", "CustomerName", "Deadline", "CreateDate", "ContainerQuantity", "LineOperatorID", "VoyageID") 
VALUES ('998877665', 'IN', 'Company E', TO_DATE('2024-12-20', 'YYYY-MM-DD'), SYSDATE, 15, 5, 1);
-- Container
INSERT INTO "Container" (
    "MaximumWeight",
    "TareWeight",
    "DateOfManufacture",
    "SizeID",
    "ContainerStatusID",
    "OwnerID",
    "ContainerTypeID",
    "VirtualBlockID",
    "LocationStatusID",
    "LineOperatorID",
    "FullStatusID"
) VALUES (
    25000,  -- MaximumWeight
    5000,   -- TareWeight
    TO_DATE('2024-01-01', 'YYYY-MM-DD'),  -- DateOfManufacture
    1,      -- SizeID
    1,      -- ContainerStatus
    3,      -- OwnerID
    2,      -- ContainerType
    null,      -- VirtualBlockID
    2,      -- LocationStatus
    3,      -- LineOperatorID
    1       -- FullStatusID
);

-- Chèn d? li?u khi LocationStatus khác 2, nên VirtualBlockID ph?i NULL
INSERT INTO "Container" (
    "MaximumWeight",
    "TareWeight",
    "DateOfManufacture",
    "SizeID",
    "ContainerStatusID",
    "OwnerID",
    "ContainerTypeID",
    "VirtualBlockID",
    "LocationStatusID",
    "LineOperatorID",
    "FullStatusID"
) VALUES (
    30000,  -- MaximumWeight
    6000,   -- TareWeight
    TO_DATE('2024-06-15', 'YYYY-MM-DD'),  -- DateOfManufacture
    2,      -- SizeID
    2,      -- ContainerStatus
    1,      -- OwnerID
    1,      -- ContainerType
    NULL,   -- VirtualBlockID (NULL vì LocationStatus khác 2)
    1,      -- LocationStatus (khác 2)
    3,      -- LineOperatorID
    2       -- FullStatusID
);

INSERT INTO "Container" (
    "MaximumWeight",
    "TareWeight",
    "DateOfManufacture",
    "SizeID",
    "ContainerStatusID",
    "OwnerID",
    "ContainerTypeID",
    "VirtualBlockID",
    "LocationStatusID",
    "LineOperatorID",
    "FullStatusID"
) VALUES (
    28000,  -- MaximumWeight
    5500,   -- TareWeight
    TO_DATE('2024-03-10', 'YYYY-MM-DD'),  -- DateOfManufacture
    1,      -- SizeID
    1,      -- ContainerStatus
    2,      -- OwnerID
    2,      -- ContainerType
    null,      -- VirtualBlockID (không NULL vì LocationStatus là 2)
    2,      -- LocationStatus
    1,      -- LineOperatorID
    1       -- FullStatusID
);

INSERT INTO "Container" (
    "MaximumWeight",
    "TareWeight",
    "DateOfManufacture",
    "SizeID",
    "ContainerStatusID",
    "OwnerID",
    "ContainerTypeID",
    "VirtualBlockID",
    "LocationStatusID",
    "LineOperatorID",
    "FullStatusID"
) VALUES (
    32000,  -- MaximumWeight
    6500,   -- TareWeight
    TO_DATE('2024-04-22', 'YYYY-MM-DD'),  -- DateOfManufacture
    2,      -- SizeID
    2,      -- ContainerStatus
    3,      -- OwnerID
    1,      -- ContainerType
    NULL,   -- VirtualBlockID (NULL vì LocationStatus khác 2)
    1,      -- LocationStatus (khác 2)
    2,      -- LineOperatorID
    2       -- FullStatusID
);

INSERT INTO "Container" (
    "MaximumWeight",
    "TareWeight",
    "DateOfManufacture",
    "SizeID",
    "ContainerStatusID",
    "OwnerID",
    "ContainerTypeID",
    "VirtualBlockID",
    "LocationStatusID",
    "LineOperatorID",
    "FullStatusID"
) VALUES (
    27000,  -- MaximumWeight
    5200,   -- TareWeight
    TO_DATE('2024-05-30', 'YYYY-MM-DD'),  -- DateOfManufacture
    2,      -- SizeID
    1,      -- ContainerStatus
    2,      -- OwnerID
    3,      -- ContainerType
    null,      -- VirtualBlockID (không NULL vì LocationStatus là 2)
    3,      -- LocationStatus
    1,      -- LineOperatorID
    1       -- FullStatusID
);

--lifeCycle
INSERT INTO "LifeCycle" ("ContainerNumber", "EntryDate", "ExitDate")
VALUES (
    1,  -- ContainerID c?a container này trong b?ng Container
    TO_DATE('2024-08-20', 'YYYY-MM-DD'),  -- Ngày nh?p bãi (EntryDate)
    NULL  -- Ch?a có ExitDate vì container v?n ?ang ? bãi
);

INSERT INTO "LifeCycle" ("ContainerNumber", "EntryDate", "ExitDate")
VALUES (
    2, 
    TO_DATE('2024-08-10', 'YYYY-MM-DD'), 
    NULL 
);
-- Container 1 ? BlockID = 1
INSERT INTO "PositionContainer" ("Status", "Bay", "RowNumber", "TierNumber", "ContainerNumber", "BlockID")
VALUES ('inactive', 1, 1, 1, 1, 1);
-- Container 2 ? BlockID = 2
INSERT INTO "PositionContainer" ("Status", "Bay", "RowNumber", "TierNumber", "ContainerNumber", "BlockID")
VALUES ('active', 2, 2, 1, 2, 2);
-- Container 3 ? BlockID = 1
INSERT INTO "PositionContainer" ("Status", "Bay", "RowNumber", "TierNumber", "ContainerNumber", "BlockID")
VALUES ('inactive', 3, 1, 2, 3, 1);
-- Container 4 ? BlockID = 2
INSERT INTO "PositionContainer" ("Status", "Bay", "RowNumber", "TierNumber", "ContainerNumber", "BlockID")
VALUES ('active', 2, 1, 1, 4, 2);
-- Container 5 ? BlockID = 1
INSERT INTO "PositionContainer" ("Status", "Bay", "RowNumber", "TierNumber", "ContainerNumber", "BlockID")
VALUES ('inactive', 2, 1, 1, 5, 1);
-- Vehicle
INSERT INTO "Vehicle" ("LicensePlate", "DriverName", "DriverContact", "VehicleCapacity", "CompanyName", "Status", "VehicleTypeID") 
VALUES ('79A-12345', 'Duy', '0912345678', 1, 'Logistics Co.', 'Active', 1);

INSERT INTO "Vehicle" ("LicensePlate", "DriverName", "DriverContact", "VehicleCapacity", "CompanyName", "Status", "VehicleTypeID") 
VALUES ('51B-67890', 'Duy', '0987654321', 1, 'Transport Corp.', 'Active', 2);

INSERT INTO "Vehicle" ("LicensePlate", "DriverName", "DriverContact", "VehicleCapacity", "CompanyName", "Status", "VehicleTypeID") 
VALUES ('29C-45678', 'Duy', '0934567890', 1, 'Freight Services', 'Inactive', 3);

INSERT INTO "Vehicle" ("LicensePlate", "DriverName", "DriverContact", "VehicleCapacity", "CompanyName", "Status", "VehicleTypeID") 
VALUES ('43D-23456', 'Duy', '0978123456', 1, 'Fast Movers', 'Active', 1);

INSERT INTO "Vehicle" ("LicensePlate", "DriverName", "DriverContact", "VehicleCapacity", "CompanyName", "Status", "VehicleTypeID") 
VALUES ('77E-78901', 'Duy', '0912123456', 1, 'Heavy Haulers', 'Inactive', 2);
-- IOManagement
INSERT INTO "IOManagement" ("CreateDate", "VehicleID", "ContainerNumber", "CommandID", "UserID") 
VALUES (SYSDATE, 1, 1, 1, 1);

INSERT INTO "IOManagement" ("CreateDate", "VehicleID", "ContainerNumber", "CommandID", "UserID") 
VALUES (SYSDATE, 2, 2, 2, 1);

INSERT INTO "IOManagement" ("CreateDate", "VehicleID", "ContainerNumber", "CommandID", "UserID") 
VALUES (SYSDATE, 3, 3, 3, 1);

INSERT INTO "IOManagement" ("CreateDate", "VehicleID", "ContainerNumber", "CommandID", "UserID") 
VALUES (SYSDATE, 4, 4, 4, 1);

INSERT INTO "IOManagement" ("CreateDate", "VehicleID", "ContainerNumber", "CommandID", "UserID") 
VALUES (SYSDATE, 5, 5, 5, 1);
--
----drop-----------------------------------------------------------------------------
--DROP TABLE "PositionContainer";
--DROP TABLE "IOManagement";
--DROP TABLE "LifeCycle";
--DROP TABLE "Container";
--DROP TABLE "Command";
--DROP TABLE "ContainerBlock";
--DROP TABLE "VirtualBlock";
--DROP TABLE "UserAccount";
--DROP TABLE "Depot";
--DROP TABLE "LineOperator";
--DROP TABLE "ContainerStatus";
--DROP TABLE "LocationStatus";
--DROP TABLE "ContainerOwner";
--DROP TABLE "ContainerType";
--DROP TABLE "Vehicle";
--DROP TABLE "VehicleType";
--DROP TABLE "ContainerSize";
--DROP TABLE "Voyage";
--DROP TABLE "Ship";
--DROP TABLE "FullStatus";